---
label: default
hide_body: false
fields:
- name: test
  type: field_group_list
  fields:
  - name: test
    type: field_group_list
    fields:
    - name: test
      type: field_group
      config: {}
      fields:
      - name: test
        type: list
        config:
          use_select: false
          min: 
          max: 
        label: test
      label: test
    config:
      min: 
      max: 
      labelField: 
    label: test
  config:
    min: 
    max: 
    labelField: 
  label: test
pages:
- index.md
